sudo: required
services:
  - docker

before_install: 
  - docker build -t shlomio/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true shlomio/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-north-1"
    app: "Docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-north-1-992382437059"
    bucket_path: "Docker"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY