FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# Not needed as it could use the files from local machine and not need to copy to container the files
COPY . . 
CMD ["npm", "run", "start"]